name: Build FSH -> IG -> GH Pages

env:
  IG_URL: https://storage.googleapis.com/ig-build/org.hl7.fhir.publisher.jar
  IG_JAR: org.hl7.fhir.publisher.jar

on:
  push:
    branches:
      - master
    paths:
      - 'fsh'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node v12
      uses: actions/setup-node@v1
      with:
        node-version: '12'

    - name: Install SUSHI
      run: npm install fsh-sushi

    - name: Run SUSHI on the 'fsh' directory, default output
      run: sushi fsh -o .

    - name: Set up Java v15
      uses: actions/setup-java@1
      with:
        java-version: 15

    - name: Set up Jekyll
      uses: helaili/jekyll-action@2.0.1

    - name: Run IG publisher
      uses: microsoft-healthcare-madison/fhir-ig-publish-action@v1